### ISSUE TITLE
Add "About" Section and Update README File

### ISSUE THREAD

**Issue by FREDVUNI** [fatuma65/africart-strapi-api#6]
**Description:**
We need to enhance the documentation for the AfricArt Strapi project by adding an "About" section. This section should provide an overview of the project, its purpose, and features.

**Tasks:**
1. **Add "About" Section:**
   - Include a brief description of the AfricArt project.
   - Highlight its features, such as:
     - E-commerce for African art.
     - Event management for artists.
     - Ticket sales for events.
     - Categories for artists.
     - Review system for tickets.

2. **Update README File:**
   - Ensure the README file reflects the new "About" section.
   - Add any relevant links or resources for users to get started.

**Additional Notes:**
- The current README is missing essential information that would help new contributors and users understand the project's scope and functionality.
- Consider reviewing existing projects for inspiration on how to format the "About" section.

**Comment by fatuma65** [comment]
The readme file has been updated by Aaron and raised a pull request on it.
